### ISSUE TITLE
Output line graph of 7 and 30 days backward moving average by python

### ISSUE THREAD

**Issue by atsushimemet** [atsushimemet/time_checker#2]
# Todo
- [x] make js dir
- [x] make python dir
- [x] update gitignore
  - [x] .env
  - [x] .ipynb_checkpoints/
- [x] make python venv
  - [x] .env
  - [x] requirements.txt
- [x] make nb in python dir
  - [x] read spreadsheet data
  - [x] change raw data to vertical holding
  - [x] complement #NUM!
  - [x] output table of 7 and 30 days backward moving average
  - [x] output line graph
  - [x] arrange in specified order
  - [x] arrange y axis max value
  - [x] arrange x axis date display
  - [x] match colors to google calendar colors
  - [x] create modules
  - [x] output log
  - [x] save image to a drive folder
  - [x] output by designated date
  - [x] update graph visualization
- [x]  cmd line chk
